### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by torigossum** [Kubajsa/randomTp#23]
Hi, I'm just having trouble figuring out how to use the spigot plugins with scalacube. I just added your rtp pluging but I'm not sure how to use it or how to tell what I can do as an admin versus what players can do

**Comment by Kubajsa** [comment]
Here's a [tutorial on how to install plugins on ScalaCube](https://scalacube.com/help/gameservers/minecraft/installing-plugins)
Then you can try the `/rtp` command if it works the plugin is working if not DM me on [Discord](https://link.jacobdev.tk/discord)
